```{r}
library(ProSpect)
library(foreach)
library(data.table)
library(Highlander)
library(magicaxis)
library(celestial)
```

```{r}
MY_filter_names = c("WFI_U38","U","B","IA484","IA527","WFI_V","IA574","V","IA598","IA624","R","WFI_Rc","IA651","IA679","IA738","IA767","I","IA797","F814W","IA856","Z","F098M","J1","F105W","J2","NB118","F125W","J3","F140W","F160W","Hs","Hl","NB209","Ks","tenisK","KsHI",
"IRAC_36","IRAC_45","IRAC_58","IRAC_80")


#setwd with ctrl shift H - /notebook/Test Folder
#filters = fread('TABLE with list of filters in order.csv') #Montague.csv ##Megatron.csv #Megatron_forR.csv surely
filters=fread('Megatron_forR.csv')
#OutputDir = 'LOCATION where the .dat files are' #I just set the wd with ctrl shift h. They're #now .csv files 
OutputDir='R-Stuff/ProSpect_Filters'
#change back to setwd("~/notebook") if you changed to prospect_filters
## getting filter response curves
filtout = foreach(ii = 1:nrow(filters))%do%{
  filtername = filters[ii,]$Name #swap name for whatver your column is called with the filter names 
  
  filt = read.csv(paste0('~/R-Stuff/ProSpect_Filters/',filtername, '.csv')) ## this should be two columns, first being wavelength in Ang, second being response
  return(approxfun(filt))
}

## getting central wavelengths
cenwave = foreach(ii = 1:nrow(filters), .combine = 'c')%do%{
  filtername = filters[ii,]$Name #swap name for whatver your column is called with the filter names 
  
  filt = read.csv(paste0('~/R-Stuff/ProSpect_Filters/',filtername, '.csv')) 
  return(cenwavefunc(filt))
}


```

```{r}
#Comb = your big table full of galaxy IDs, fluxes and flux errors (in Jy)
Comb = fread('ProSpect-ZFOURGE-Forrest.csv',sep=',')
#Change UID & column names here to match whatever its called in your catalogue 
getinfo=function(CAT=574689){
  ## grabbing out your galaxy ID and all the flux columns and then flux_err colums 
  ## swap these to be the right names but keep them in wavelength order 
  
  out=Comb[id==CAT,list(id,WFI_U38,U,B,IA484,IA527,WFI_V,IA574,V,IA598,IA624,R,WFI_Rc,IA651,IA679,IA738,IA767,I,
IA797,F814W,IA856,Z,F098M,J1,F105W,J2,NB118,F125W,J3,F140W,F160W,Hs,Hl,NB209,Ks,tenisK,KsHI,
IRAC_36,IRAC_45,IRAC_58,IRAC_80,WFI_U38_err,U_err,B_err,IA484_err,IA527_err,WFI_V_err,IA574_err,V_err,IA598_err,IA624_err,R_err,WFI_Rc_err,IA651_err,IA679_err,IA738_err,IA767_err,I_err,
IA797_err,F814W_err,IA856_err,Z_err,F098M_err,J1_err,F105W_err,J2_err,NB118_err,F125W_err,J3_err,F140W_err,F160W_err,Hs_err,Hl_err,NB209_err,Ks_err,tenisK_err,KsHI_err,
IRAC_36_err,IRAC_45_err,IRAC_58_err,IRAC_80_err)]
  ## splitting out all your fluxes
  flux=out[,list(WFI_U38,U,B,IA484,IA527,WFI_V,IA574,V,IA598,IA624,R,WFI_Rc,IA651,IA679,IA738,IA767,I,
IA797,F814W,IA856,Z,F098M,J1,F105W,J2,NB118,F125W,J3,F140W,F160W,Hs,Hl,NB209,Ks,tenisK,KsHI,
IRAC_36,IRAC_45,IRAC_58,IRAC_80)]
  ## and flux errors 
  fluxerr=out[,list(WFI_U38_err,U_err,B_err,IA484_err,IA527_err,WFI_V_err,IA574_err,V_err,IA598_err,IA624_err,R_err,WFI_Rc_err,IA651_err,IA679_err,IA738_err,IA767_err,I_err,
IA797_err,F814W_err,IA856_err,Z_err,F098M_err,J1_err,F105W_err,J2_err,NB118_err,F125W_err,J3_err,F140W_err,F160W_err,Hs_err,Hl_err,NB209_err,Ks_err,tenisK_err,KsHI_err,
IRAC_36_err,IRAC_45_err,IRAC_58_err,IRAC_80_err)]
  ## putting them into two columns 
  flux=cbind(flux=as.numeric(flux),fluxerr=as.numeric(fluxerr))

  ## ADDING A 10% ERROR FLOOR TO EACH BAND'S ERROR -- Optional
  #floor = rep(0.1, 22)
  #for(ii in 1:length(fluxerr)){
    #fluxerr[[ii]]=sqrt(fluxerr[[ii]]^2+(flux[,'flux'][[ii]]*floor[ii])^2)
  #}
  
  flux=cbind(flux=as.numeric(flux[,'flux']),fluxerr=as.numeric(fluxerr))
  
  ## SETTING NEGATIVE FLUXES TO ZERO
  flux[flux<0]=0
  
  ## adding columns with your filter names and central wavelengths 
  data_table = data.table(filters, cenwave)
  flux=cbind(data_table, flux)
  return(list(Lv01=out,flux=flux))
}
```

```{r}
redshift=Comb[id == 17374,]$redshift
agemax = 13.3e9-cosdistTravelTime(z=redshift, ref = '737')
LumDist_Mpc = cosdistLumDist(z=redshift, ref = '737') ## this just speeds up the calculations 
Data=list(flux= getinfo(17374)$flux,
          arglist=list(z=redshift, 
                       emission=TRUE,
                       massfunc=massfunc_snorm_trunc, ### use this to change SFH parameterisations -- use ?massfunc to see some of the inbuilt options 
                       agemax=agemax, 
                       Zagemax = (agemax/1e9),
                       magemax=(agemax/1e9), 
                       Z=Zfunc_massmap_lin, ### THIS CHANGES THE METALLICITY HISTORY 
                       LumDist_Mpc=LumDist_Mpc),
          speclib=BC03lr, 
          Dale=Dale_NormTot, 
          filtout=filtout, 
          Dale_M2L_func=Dale_M2L_func, # required to get monitored dust masses
          SFH=SFHfunc, 
          parm.names=c('mSFR','mpeak','mperiod','mskew','tau_birth','tau_screen', 'alpha_SF_birth','alpha_SF_screen', 'Zfinal'), # which parameters to fit for
          mon.names=c("LP","masstot","dustmass.birth", "dustmass.screen", "dustmass.total", "dustlum.birth", "dustlum.screen", "dustlum.total", "SFRburst"),# paste("flux.",filters,sep='')),  # some of the things you may wish to monitor in each step of the chain
          logged=c(T,F,T,F,T,T,F,F,T), # fit parameters in logged or linear space
          intervals=list(lo=c(-4,-2,-1,-0.5,-2.5,-2.5,0,0,-4), 
                         hi=c(3,1,1,1,1.5,1,4,4,-1.3)), # fitting range for parameters
          fit = 'LD', # specifies the way in which the SED should be fitted ('LD', 'optim', 'CMA', or 'check')
          N=length(MY_filter_names), # number of observed filters
          like='st', # Using a student-t likelihood
          verbose=FALSE 
  )
```

```{r}
startpoint = (Data$intervals$lo+Data$intervals$hi)/2
seed=1
testHigh = Highlander(startpoint, Data, ProSpectSEDlike, Niters=c(200,200), NfinalMCMC = 200, lower = Data$intervals$lo, upper=Data$intervals$hi, seed=seed, optim_iters = 2, likefunctype = 'LD' )
```

```{r}
Data$fit = 'check'
bestfit=ProSpectSEDlike(testHigh$par, Data=Data)
```

```{r}

```

```{r}
```
